### PR TITLE
added my intro and linked readme.md

### LINKED ISSUE #2: 2. Introduce Abdul
__As a site visitor, I want to learn more about Abdul__

### Repo

- [x] developed on a branch named `abdul`

### abdul.md

- [x] create the file
- [x] add their name as the main title
- [x] write a paragraph introduction
- [x] create a link back to the README

### README.md

- [x] change their list item into a link

### PR DESCRIPTION
**Pull request by aame1**
Hi @fmkarakus, 

I added my intro and linked the README.md. 

Could you review it, please? 

Thank you,

Abdul.

### CODE REVIEW

**Review by fmkarakus — COMMENTED** [review]
It says no changes. I cant see the content of abdul.md or the change in readme file.

**Comment by aame1** [comment]
@fmkarakus  : now it should be good. VSC was messing with me. :)

**Comment by aame1** [comment]
> It says no changes. I cant see the content of abdul.md or the change in readme file.

now it should be good. VSC was messing with me. :)

**Review by fmkarakus — COMMENTED** [review]
Nice! We can merge it after the group reviews it. (You can link your issue to your PR.)

**Comment by fmkarakus** [comment]
closes #2

**Pull request merged**
